spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://teamicu.men:4321/testsql?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: testSql
    password: testSql114514
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8002