spring:
  datasource:
    url: jdbc:mysql://teamicu.men:4321/testsql?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: testSql
    password: testSql114514

server:
  port: 8001