spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebidding_account?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

server:
  port: 8001