spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebidding-bwic?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root1234

server:
  port: 8003
